### ISSUE TITLE
生成message_id失败，此消息大概率被风控了。

### ISSUE THREAD

**Issue by Drew-Jay** [takayama-lily/onebot#19]
日志里显示
```
生成message_id失败，此消息大概率被风控了。
此消息将尝试以另一种方式再发送一次。
```
这种类型的消息，在mac qq 和iPhone看起来是一个转发的图文消息，可以点开，看到内容
但是在Android手机看来就是”[图文消息]“这几个文字

问：

1. 被风控的是tx的某种策略是吗，有没有可能通过例如充会员等方式避免呢
2. 如果无法不免风控，Android手机是否也能看到转发的问题消息列表，而不是"[图文消息]"几个字呢

**Comment by Drew-Jay** [comment]
不能充会员避免，好了我知道了

**Comment by takayama-lily** [comment]
消息长度大概是多少？
bot的q龄大概是多少？

**Comment by takayama-lily** [comment]
1. 大概在前天tx应该修改了风控策略，导致大范围出现被风控的情况，表现为长一点的消息无法发出（不仅限于bot，官方客户端一样无法发出这类消息）
2. 目前已知被风控的几乎都是注册时间一年半以下的账号（样本数可能不足无法下定论）
3. 另外我遇到这类状况点击 `图文消息` 也仍然看不到内容，会提示加载失败。可以看到内容我感觉有些神奇

**风控问题已经暂时解决，更新依赖即可**
