### ISSUE TITLE
online状态问题导致post方式无法调用api

### ISSUE THREAD

**Issue by moemoechu** [takayama-lily/onebot#2]
![image](https://user-images.githubusercontent.com/6707029/94326105-99667600-ffd4-11ea-98c7-47e5ccf336c1.png)
断线重连的时候会有system.offline消息，并且会发送disable元事件，但是上线的时候好像不会发system.online消息，导致http的post方式调用api会失败，感觉应该是没更新online状态导致。
![image](https://user-images.githubusercontent.com/6707029/94326182-067a0b80-ffd5-11ea-8a7c-4fadc2f7b19f.png)
![image](https://user-images.githubusercontent.com/6707029/94326189-0e39b000-ffd5-11ea-8ac9-558fe2ca08cf.png)
![image](https://user-images.githubusercontent.com/6707029/94326376-0af2f400-ffd6-11ea-8023-2738b118b8e8.png)

**Comment by takayama-lily** [comment]
断线的原因是啥？另一处登陆了？

**Comment by moemoechu** [comment]
本地运行，断线就是普通的wifi切换了。

**Comment by takayama-lily** [comment]
无法再现，网络断开的情况一定会触发disable和enable的，不可能只触发disable。
你的内核版本是最新的1.7.2吗？

**Comment by moemoechu** [comment]
![image](https://user-images.githubusercontent.com/6707029/94327382-35947b00-ffdd-11ea-919b-3e182f91db7f.png)

是1.7.2，不过抛开网络断开不看，我直接启动之后，也是无法使用post方式调用api，难道是配置或者账号什么的有问题。
我把core.js里面关于online的判断注释掉就能正常。
难道是。。。。。我换个系统试试看。

**Comment by takayama-lily** [comment]
可能是内核里的bug。使用`npm up`更新到1.7.3试一下应该好了。

**Comment by moemoechu** [comment]
牛皮，可以了👍。
