### ISSUE TITLE
请问可以通过post请求send_group_msg吗

### ISSUE THREAD

**Issue by Nakasu-ksm** [takayama-lily/onebot#20]
请问可以通过post请求send_group_msg吗,我试了只有GET可以

**Comment by takayama-lily** [comment]
可以，post支持以下两种content-type：
json和x-www-form-urlencoded

如未设置content-type目前会按json解析

**Comment by Nakasu-ksm** [comment]
可是我试了不行啊，node里面显示接收到post请求但是消息没发出啊

**Comment by takayama-lily** [comment]
能否贴一下post的header和body

**Comment by wenshitao** [comment]
<?php
require 'vendor/autoload.php';
use QL\QueryList;
$message = $_POST['message'];
$data = QueryList::get("http://127.0.0.1:5700/send_group_msg?message=$message&group_id=924614085")->getHtml();
var_dump($data);
?>

**Comment by wenshitao** [comment]
require 'vendor/autoload.php';
use QL\QueryList;
$message = $_POST['message'];
$data = QueryList::get("http://127.0.0.1:5700/send_group_msg?message=$message&group_id=924614085")->getHtml();
var_dump($data);

**Comment by wenshitao** [comment]
require 'vendor/autoload.php';
use QL\QueryList;
$message = $_POST['message'];
$data = QueryList::get("http://127.0.0.1:5700/send_group_msg?message=$message&group_id=xxxx")->getHtml();
var_dump($data);

**Comment by Nakasu-ksm** [comment]
感谢

**Comment by wenshitao** [comment]
require 'vendor/autoload.php';
use QL\QueryList;
$message = $_POST['message'];
$data = QueryList::post("http://127.0.0.1:5700/send_group_msg",[
    'message' => $message,
    'group_id' => '924614085'
])->getHtml();
var_dump($data);

**Comment by wenshitao** [comment]
require 'vendor/autoload.php';
use QL\QueryList;
$message = $_POST['message'];
$data = QueryList::post("http://127.0.0.1:5700/send_group_msg",[
    'message' => $message,
    'group_id' => 'xxxxx'
])->getHtml();
var_dump($data);

**Comment by wenshitao** [comment]
感谢！我弄好了，用QL的post可以，但是curl貌似不行
