### ISSUE TITLE
BUG请解决一下谢谢

### ISSUE THREAD

**Issue by Nakasu-ksm** [takayama-lily/onebot#22]
(node:9988) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "iterable" argument must be an instance of Iterable. Received null
    at from (internal/streams/from.js:31:11)
    at Function.Readable.from (_stream_readable.js:1204:10)
    at AndroidClient.decodeLoginResponse (E:\onebot-master\node_modules\oicq\lib\wtlogin\wt.js:422:29)
    at AndroidClient.captchaLogin (E:\onebot-master\node_modules\oicq\lib\wtlogin\wt.js:199:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:9988) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9988) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by takayama-lily** [comment]
没有遇见过该问题，暂时无法复现。
是每次输入验证码就一定发生吗？
能否提供一下nodejs版本和连接到的ip地址？
使用的是默认的平板协议吗？

**Comment by Nakasu-ksm** [comment]
现在好像直接显示什么禁止登录-无法登录qq请更换设备或网络环境

**Comment by Nakasu-ksm** [comment]
更换了一下环境并升级内核解决了非常感谢
