### ISSUE TITLE
[需求建议]希望长信息可配置固定使用分片发送

### ISSUE THREAD

**Issue by NepPure** [takayama-lily/onebot#25]
现在大多数情况长信息几乎100%生成Id失败，是否考虑加一个配置项，让长信息使用分片发送的方式？

这样是否对避免风控更友好一点

**Comment by takayama-lily** [comment]
没有id是因为还未实现分片消息的id生成，我会考虑实现这个。

**Comment by NepPure** [comment]
原来如此！
