### ISSUE TITLE
[建议]以package形式发布

### ISSUE THREAD

**Issue by woshiguabi** [takayama-lily/onebot#26]
下载源码是不是太奇怪了一点？也不方便其他方式的拓展

**Comment by takayama-lily** [comment]
你是指发布为npm的package吗？
如果有需要建议你使用 [oicq](https://github.com/takayama-lily/oicq) 来开发你的应用程序或框架。
API设计的非常简洁，任何熟悉Node.js的人都可以快速上手。
至于这个基于http通信的项目，更偏向一种过渡性的产品。
而且本身就包含完整的功能，是直接拿来使用的，没有必要作为库发布了。

**Comment by woshiguabi** [comment]
我计划开发可运行在onebot规范上的应用程序框架，虽然并不打算与具体的onebot实现绑定，但考虑找一个支持npm包管理的onebot实现作为默认选项

**Comment by takayama-lily** [comment]
没啥意义啊，用npm安装后会到node_modules文件夹里去，但现在这个必须作为入口运行的。
即使发布为package用户也不可能通过npm命令来安装。
你说要把程序改成可以import后自己调用的形式，目前没这个打算= =
如果你想这么做可以fork后自己修改发布，也可以给我pr我来发布。作为一个lib形式的版本。

**Comment by takayama-lily** [comment]
好了，现在有package了
