### ISSUE TITLE
关闭nonebot2之后，需要重启onebot才能连上ws反向代理

### ISSUE THREAD

**Issue by anaivebird** [takayama-lily/onebot#27]
先打开nonebot2，接着打开onebot，可以连接上

这时候关闭nonebot2（onebot还是开着），再打开nonebot2，ws反向代理连不上

**Comment by takayama-lily** [comment]
无法重现
日志里是否一直在报 `反向ws连接(xxxxxx)被关闭，将在3000毫秒后尝试连接`
并且你重新开启对向的ws服务端却连接不上？

**Comment by anaivebird** [comment]
不是，
[2020-12-23T23:50:39.343] [ERROR] [BOT:我的qq号] - 反向ws连接(ws://127.0.0.1:8080/cqhttp/ws)被关闭，将在3000毫秒后尝试连接。
[2020-12-23T23:50:42.349] [INFO] [BOT:我的qq号] - 反向ws连接(ws://127.0.0.1:8080/cqhttp/ws)连接成功。

就是我没有开nonebot2，他都能连接成功，不知道和谁连接了

我查了下端口占用8080端口并没有除了oicq之外的进程占用

**Comment by takayama-lily** [comment]
等等，你不会是和自己连接了，吧？
你没有把机器人监听的port设置为8080对吧？

**Comment by anaivebird** [comment]
general: {
        platform:           1,      //1手机 2平板 3手表 4Mac
        ignore_self:        false,   //群聊和私聊是否无视自己的发言
        resend:             true,   //被风控的消息是否尝试以分片再次发送（分片是一种古老的消息，暂不支持撤回等操作）
        debug:              false,  //开启debug
        use_cqhttp_notice:  false,  //是否使用cqhttp标准的notice事件格式

        host:               "0.0.0.0",  //监听主机名
        port:               8080,       //端口
        use_http:           false,      //启用http
        use_ws:             true,      //启用ws，和http使用相同端口
        access_token:       "",         //访问api的token
        secret:             "",         //上报数据的sha1签名密钥
        post_timeout:       30,         //post超时时间(秒)
        post_message_format:"string",   //string或array
        enable_cors:        false,      //是否允许跨域请求
        enable_heartbeat:   true,      //是否启用ws心跳
        heartbeat_interval: 15000,      //ws心跳间隔
        rate_limit_interval:500,        //使用_rate_limited后缀限速调用api的排队间隔时间(毫秒)
        event_filter:       "",         //json格式的事件过滤器文件路径
        post_url: [ //上报地址，可以添加多个url
            // "http://your.address.com:80",
        ],
        ws_reverse_url: [ //反向ws地址，可以添加多个url(暂不支持将api和event分两个通道)
            "ws://127.0.0.1:8080/cqhttp/ws",
        ],
        ws_reverse_reconnect_interval: 3000, //反向ws断线重连间隔(毫秒)
    },

可能还真是。。

**Comment by anaivebird** [comment]
谢了，破案了
nonebot2的官方文档是8080端口，可能还得跟新手说下，中招了
