### ISSUE TITLE
如何完成滑动验证码并取得ticket

### ISSUE THREAD

**Issue by takayama-lily** [takayama-lily/onebot#28]
> 更新到最新版本
> 提示收到滑动验证码后：
1. **用chrome浏览器访问给出的url，并打开F12->Network (网络)**
![QQ截图20201226052508](https://user-images.githubusercontent.com/12014361/103141662-cbee4f00-473a-11eb-9a50-6f7baaf9a99b.png)
2. **滑动后会发一个请求，从响应中复制出ticket并输入**
![QQ截图20201226052740](https://user-images.githubusercontent.com/12014361/103141677-18d22580-473b-11eb-9412-2d4a24af9364.png)
> ticket输入错误会报环境异常，重复上述过程即可
> 理论上在同一IP或同一设备只需要进行一次

**Comment by wdssmq** [comment]
允许复制整行信息（鼠标点三下）
```js
function ticketPick(input) {
    // console.log(input);
    input = input.toString().trim();
    if (input.indexOf("ticket:") > -1) {
        return input.split('"')[1];
    }
    return input;
}
```

**Comment by TheSnowfield** [comment]
> 允许复制整行信息（鼠标点三下）
> 
> ```js
> function ticketPick(input) {
>     // console.log(input);
>     input = input.toString().trim();
>     if (input.indexOf("ticket:") > -1) {
>         return input.split('"')[1];
>     }
>     return input;
> }
> ```

在滑動驗證碼完成之後
通常情況下在Chrome的控制台内會有一個 `jsbridge://`的錯誤. 不出意外它後邊就是Ticket

**Comment by Kun-GitHub** [comment]
滑动后会发一个请求，从响应中复制出ticket并输入.
==========================================
在哪输入啊？没看到可以输入的地方啊，拼接在浏览器后面输入？vs code跑的oicq又没法输入，webstorm跑的也没法输入，请问在哪输入？

**Comment by a1014068504** [comment]
邮件已收到~

**Comment by DeepView** [comment]
滑动验证后，发现ticket是空的，什么都没有，这就很奇怪了，难道腾讯已经修复了这个问题吗？

**Comment by Cupcc** [comment]
我活的ticket 填写后验证显示禁止登陆。
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/53716543/222919611-72954aa3-0e6c-4235-9068-f82614f232e1.png">

**Comment by wdssmq** [comment]
> 我活的ticket 填写后验证显示禁止登陆。 <img alt="image" width="1047" src="https://user-images.githubusercontent.com/53716543/222919611-72954aa3-0e6c-4235-9068-f82614f232e1.png">

无法登录的临时处理方案 | MiraiForum
https://mirai.mamoe.net/topic/223/%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95%E7%9A%84%E4%B8%B4%E6%97%B6%E5%A4%84%E7%90%86%E6%96%B9%E6%A1%88?lang=zh-CN

**Comment by madobet** [comment]
失败多次被限制的教训：不要用firefox，找不到那条 verify

**Comment by nullptr555** [comment]
![image](https://github.com/user-attachments/assets/484869a2-2fbb-4754-88d3-75539f9cd77a)
这个我获取到ticket之后，在控制台输入也没反应，一直这样无线循环

**Comment by a1014068504** [comment]
邮件已收到~

**Comment by Perxenic-Acid** [comment]
![Image](https://github.com/user-attachments/assets/131cd800-20b0-4186-a955-b9f00fc40571)

获取ticket之后如何输入？这里无论是键盘敲字还是 ctrl + v 均无法输入任何文本

**Comment by a1014068504** [comment]
邮件已收到~
