### ISSUE TITLE
一个转码问题

### ISSUE THREAD

**Issue by Nakasu-ksm** [takayama-lily/onebot#29]
音频转码到amr失败，请确认你的ffmpeg可以处理此转换。
转换的是m4a文件,请解决谢谢

**Comment by takayama-lily** [comment]
在配置里打开debug，ffmpeg会有错误输出
能否贴一下这个错误

**Comment by Nakasu-ksm** [comment]
ffmpeg error: Error: Command failed: ffmpeg -y -i E:\onebot-master\data\record\0.99036006341339581608962421769 -ac 1 -ar 8000 -f amr E:\onebot-master\data\record\aedaf734583eed875fb0323085e0575f
'ffmpeg' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

[2020-12-26T14:00:21.800] [DEBUG] [BOT:1398087940] - ffmpeg output: 'ffmpeg' �����ڲ����ⲿ���Ҳ���ǿ��� �еĳ���
���������ļ���

[2020-12-26T14:00:21.808] [WARN] [BOT:1398087940] - 音频转码到amr失败，请确认你的ffmpeg可以处理此转换。

**Comment by Nakasu-ksm** [comment]
感谢

**Comment by takayama-lily** [comment]
你的系统里没装ffmpeg？
http://ffmpeg.org/download.html
需要下载安装加入环境变量path中才行哦。

**Comment by dora-world** [comment]
ok
谢谢

**Comment by dora-world** [comment]
我明白怎么用了

**Comment by dora-world** [comment]
非常感谢

**Comment by Nakasu-ksm** [comment]
好的我去试试谢谢啦

**Comment by Nakasu-ksm** [comment]
解决了但是请问为什么转换出来特别不清晰啊

**Comment by takayama-lily** [comment]
> 解决了但是请问为什么转换出来特别不清晰啊

因为amr的码率很低，qq语音只允许这么低的码率没办法

**Comment by takayama-lily** [comment]
据说SILK格式可能会稍好，但是ffmpeg不支持转换。
你可以自己想办法转换成SILK，看看会不会好些。

**Comment by Nakasu-ksm** [comment]
好的谢谢啦
