### ISSUE TITLE
使用PM2启动时watch问题

### ISSUE THREAD

**Issue by LANPAST** [takayama-lily/onebot#30]
使用PM2启动main.js,添加了--watch参数之后,查看pm2 logs会无限提示"正在检查&更新内核版本.."
如图
![图片](https://user-images.githubusercontent.com/29109822/103184824-ac028b00-48f4-11eb-9f78-8b00511c1469.png)

**Comment by takayama-lily** [comment]
因为程序启动时会自动更新依赖到最新版本
--watch监听到node_module内变化就自动重启程序了，无限套娃
临时解决办法是不要添加--watch参数，或者屏蔽main.js内的`npm up`相关代码
