### ISSUE TITLE
已经重命名一直重复提示

### ISSUE THREAD

**Issue by AoaoMH** [takayama-lily/onebot#31]
![image](https://user-images.githubusercontent.com/29968512/103207784-286b8d00-493a-11eb-8def-79423d0f559d.png)
![image](https://user-images.githubusercontent.com/29968512/103207792-2d304100-493a-11eb-9516-0e6980ef8db8.png)

**Comment by takayama-lily** [comment]
看报错应该是json语法错误了，
检查一下配置文件内容有没有改错

**Comment by AoaoMH** [comment]
> 看报错应该是json语法错误了，
> 检查一下配置文件内容有没有改错

发现是少了个逗号，已解决
又遇到了个问题是一直报这个
![image](https://user-images.githubusercontent.com/29968512/103212360-85207500-4945-11eb-85ee-c537b53ee523.png)


配置如下：
![image](https://user-images.githubusercontent.com/29968512/103212402-a2554380-4945-11eb-8bad-5f2692053b37.png)

**Comment by takayama-lily** [comment]
这应该是你的ws服务端的问题，我无法帮你解决哦

**Comment by AoaoMH** [comment]
> 这应该是你的ws服务端的问题，我无法帮你解决哦

好的，我再研究一下，感谢。
