### ISSUE TITLE
TX服务器抽风

### ISSUE THREAD

**Issue by Xxpain** [takayama-lily/onebot#32]
![image](https://user-images.githubusercontent.com/44777634/103264096-a2585080-49e4-11eb-8251-3bc73cfdf7e4.png)
😢😢

**Comment by takayama-lily** [comment]
重连后可以正常使用吗？

**Comment by Xxpain** [comment]
> 重连后可以正常使用吗？

修改了一下hosts文件 换了好几个ip, 重启一下,  报了个这个错,然后好像恢复正常了
![image](https://user-images.githubusercontent.com/44777634/103265519-bbfb9700-49e8-11eb-8ce7-db8e33b7acb7.png)

**Comment by takayama-lily** [comment]
恩，腾讯服务器又开始抽风了，手动指定ip是可以解决的
