### ISSUE TITLE
Send faild 120 是什么奇怪的错误

### ISSUE THREAD

**Issue by NepPure** [takayama-lily/onebot#33]
![image](https://user-images.githubusercontent.com/12379907/105003585-ccde7c00-5a6d-11eb-8158-652c25f47bc6.png)

**Comment by NepPure** [comment]
关了几分钟重启又好了 :(

**Comment by takayama-lily** [comment]
被禁言了

**Comment by NepPure** [comment]
好像不是，我记得当时登陆TIM试了下 还能正常发送，我再确认一下
