### ISSUE TITLE
get_version_info 返回值有误

### ISSUE THREAD

**Issue by Steve-xmh** [takayama-lily/onebot#34]
> 琢磨着要不要发在 node-oicq 里去，毕竟这个 bug 出在 node-oicq 影响了 node-onebot（雾）

`data` 字段直接包含了 package.json ....，这样强行组合的话不符合 [onebot 中对该 API 的规范](https://github.com/howmanybots/onebot/blob/master/v11/specs/api/public.md#get_version_info-%E8%8E%B7%E5%8F%96%E7%89%88%E6%9C%AC%E4%BF%A1%E6%81%AF)：

> ## `get_version_info` 获取版本信息
> ### 参数
> 无
> ### 响应数据
> | 字段名 | 数据类型 | 说明 |
> | ----- | ------- | --- |
> | `app_name` | string | 应用标识，如 `mirai-native` |
> | `app_version` | string | 应用版本，如 `1.2.3` |
> | `protocol_version` | string | OneBot 标准版本，如 `v11` |
> | …… | - | OneBot 实现自行添加的其它内容 |
也就是无法正确获取 `app_name` 和 `app_version` 等参数，得用 `name` 和 `version`（按照 package.json 写法的话），`protocol_version` 也没有提供

修改的话在 [`oicq/client.js` 的 683 行](https://github.com/takayama-lily/oicq/blob/ad4e91c19b6d2a12f07132a3d5f39de1baeefa13/client.js#L683)左右：
```js
// ...
    getVersionInfo() {
        return buildApiRet(0, version);
    }
// ...
```
改成以下即可：
```js
// ...
    getVersionInfo() {
        const result = Object.assign({}, version);
        result.app_name = result.name;
        result.app_version = result.version;
        result.protocol_version = "v11";
        return buildApiRet(0, result);
    }
// ...
```
可能会有点消耗性能，可以看情况稍微优化，谢谢大佬了

**Comment by takayama-lily** [comment]
这个好像不是很重要，有空我加一下吧(或者你pr一个

**Comment by Steve-xmh** [comment]
> 这个好像不是很重要，有空我加一下吧(或者你pr一个

的确不是太重要，只是在做一个 OneBot UI 前端的时候遇到的就提了一下
