### ISSUE TITLE
发送at,手机无法显示@符号

### ISSUE THREAD

**Issue by SatoriNya** [takayama-lily/onebot#35]
发送at,手机无法显示@符号,只有群昵称,电脑端正常
![QQ截图20210125002620](https://user-images.githubusercontent.com/43024829/105636684-507add00-5e61-11eb-89df-b390fdc897f9.png)
![QQ截图20210125002633](https://user-images.githubusercontent.com/43024829/105636685-52dd3700-5e61-11eb-916f-a70c75c7c8fe.png)

**Comment by takayama-lily** [comment]
这个问题很久之前就修复了
你的依赖版本可能太旧了，需要执行`npm up`更新一下

**Comment by SatoriNya** [comment]
确实是这样,非常感谢!
