### ISSUE TITLE
解读路径时可以使用转义符么？

### ISSUE THREAD

**Issue by conanhsj** [takayama-lily/onebot#39]
使用习惯里在文件夹中使用了“[”和“]”符号，导致于图片路径解读时出现了错误。
虽然可以用更换文件夹路径的方式避开，但是想问一下有办法通过转义符之类的方式来兼容么？

**Comment by takayama-lily** [comment]
转义符：
[ = `&#91;`
] = `&#93;`

推荐使用数组传参，可以不用转义
