### ISSUE TITLE
关于容器内部署的健康检查

### ISSUE THREAD

**Issue by StoneShiLei** [takayama-lily/onebot#48]
最近将bot服务迁移到了k8s内，遇到一个问题，当因为某些原因无法正常连接ws的时候，会不断尝试重连：反向ws连接被关闭，将在xxxxx毫秒后尝试连接。
我需要该bot服务在发生断线后，发生异常停止服务而不是不断尝试断线重连，这样容器才能监测到bot服务已不再健康，重启容器。
是否有配置项可以关闭ws断线重连，或者是否有tcp or http的健康检测端口？

**Comment by takayama-lily** [comment]
可以加一个`ws_reverse_reconnect_interval`设置为0的时候不自动重连

**Comment by StoneShiLei** [comment]
ws_reverse_reconnect_interval设置为0的时候仅仅是重连的延迟变为0毫秒了。。

**Comment by takayama-lily** [comment]
感觉0不太好，设为负数的时候不重连吧。需pull

**Comment by StoneShiLei** [comment]
好的

**Comment by StoneShiLei** [comment]
> 
> 
> 感觉0不太好，设为负数的时候不重连吧。需pull

emmmmm试了下，目前的逻辑是设置为-1后仅仅是不再重连，但进程没有退出，所以容器认为应用仍然在正常运行，能否考虑抛出异常直接中断主进程或以tcp或http接口提供健康检测呢，比如程序进入非正常状态下，访问其某个http接口返回值为500这样，正常情况返回200

**Comment by takayama-lily** [comment]
不合理，只是断了一个ws，程序没有进入非正常状态
不明白你遇到了什么问题必须要程序退出重启
