### ISSUE TITLE
我想问一下  这个项目支持  设置发送频率 吗

### ISSUE THREAD

**Issue by xxxxue** [takayama-lily/onebot#5]
我想问一下  这个项目支持 设置 发送消息的 频率 吗
比如 10秒内 只允许发一条, 其他的消息 在后面排队. 按照顺序慢慢发.
发送太快. 容易封号

**Comment by takayama-lily** [comment]
暂时还未支持

**Comment by takayama-lily** [comment]
你好，在你的建议下，已经添加了这个特性。
