### ISSUE TITLE
无法登陆QQ

### ISSUE THREAD

**Issue by huagjichen** [takayama-lily/onebot#57]
如果是密码登录就会提示这个：[温馨提示]当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面(错误码：235)

如果是扫码登录，就会在手机端提示“当前设备网络不稳定或处于复杂网络环境，为了你的安全建议将两个设备连接同一网络...”

我尝试了将配置文件里的platform:      1,      //1:安卓手机 2:aPad 3:安卓手表 4:MacOS 5:iPad，          依次设置成1,4,5。
换了3个QQ号。
换个两部扫码的手机。

但是，以上两种登录失败情况均会出现，无法登陆。

**Comment by a1014068504** [comment]
邮件已收到~

**Comment by huagjichen** [comment]
端口全开。有时候可以收到滑块验证，但是发了ticket也依旧提示版本过低：[温馨提示]当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面(错误码：235)

**Comment by huagjichen** [comment]
问题已解决，在本地登录好，然后复制token即可
