### ISSUE TITLE
chatgpt 出现故障！

### ISSUE THREAD

**Issue by Wileysec** [takayama-lily/onebot#58]
出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。
That model does not exist

**Comment by a1014068504** [comment]
邮件已收到~

**Comment by Wileysec** [comment]
2023-02-16 07:41:49.026 | INFO     | graia.ariadne.model:log:83 - 3365977521: [RECV][L(1162081675)] -> hello


2023-02-16 07:41:49.719 | ERROR    | __main__:handle_message:75 - That model does not exist


Traceback (most recent call last):




  File "/app/bot.py", line 84, in friend_message_listener


    response = await handle_message(friend, f"friend-{friend.id}", chain.display, source)


                     │              │                              │     │        └ Source(id=37281, time=datetime.datetime(2023, 2, 16, 7, 41, 48, tzinfo=datetime.timezone.utc), type='Source')


                     │              │                              │     └ <property object at 0x7f96385ffd10>


                     │              │                              └ MessageChain([Plain(text='hello')])


                     │              └ Friend(id=1162081675, nickname='L', remark='L')


                     └ <function handle_message at 0x7f9636709c10>




> File "/app/bot.py", line 70, in handle_message


    resp = await session.get_chat_response(message)


                 │       │                 └ 'hello'


                 │       └ <function ChatSession.get_chat_response at 0x7f9636ff4c10>


                 └ <chatbot.ChatSession object at 0x7f9636741160>




  File "/app/chatbot.py", line 51, in get_chat_response


    final_resp = await loop.run_in_executor(None, bot.ask, message, config.openai.temperature)


                       │    │                     │   │    │        │      │      └ 0.5


                       │    │                     │   │    │        │      └ OpenAIAPIKey(temperature=0.5, Authorization=None, proxy=None, driver_exec_path=None, browser_exec_path=None, conversation=Non...


                       │    │                     │   │    │        └ Config(mirai=Mirai(qq=3365977521, api_key='1234567890', http_url='http://mirai:8080', ws_url='http://mirai:8080'), openai=Ope...


                       │    │                     │   │    └ 'hello'


                       │    │                     │   └ <function Chatbot.ask at 0x7f96372681f0>


                       │    │                     └ <revChatGPT.Official.Chatbot object at 0x7f96384c50d0>


                       │    └ <function BaseEventLoop.run_in_executor at 0x7f963993e280>


                       └ <_UnixSelectorEventLoop running=True closed=False debug=False>




  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run


    result = self.fn(*self.args, **self.kwargs)


             │        │            └ None


             │        └ None


             └ None


  File "/usr/local/lib/python3.9/site-packages/revChatGPT/Official.py", line 139, in ask


    completion = self._get_completion(


                 │    └ <function Chatbot._get_completion at 0x7f9637268040>


                 └ <revChatGPT.Official.Chatbot object at 0x7f96384c50d0>


  File "/usr/local/lib/python3.9/site-packages/revChatGPT/Official.py", line 64, in _get_completion


    return openai.Completion.create(


           │      │          └ <classmethod object at 0x7f96384c5c10>


           │      └ <class 'openai.api_resources.completion.Completion'>


           └ <module 'openai' from '/usr/local/lib/python3.9/site-packages/openai/__init__.py'>


  File "/usr/local/lib/python3.9/site-packages/openai/api_resources/completion.py", line 25, in create


    return super().create(*args, **kwargs)


                           │       └ {'engine': 'text-chat-davinci-002-20221122', 'prompt': 'You are ChatGPT, a large language model trained by OpenAI. Respond co...


                           └ ()


  File "/usr/local/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create


    response, _, api_key = requestor.request(


                           │         └ <function APIRequestor.request at 0x7f9639771ca0>


                           └ <openai.api_requestor.APIRequestor object at 0x7f9635db1340>


  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 226, in request


    resp, got_stream = self._interpret_response(result, stream)


                       │    │                   │       └ False


                       │    │                   └ <Response [404]>


                       │    └ <function APIRequestor._interpret_response at 0x7f9639777160>


                       └ <openai.api_requestor.APIRequestor object at 0x7f9635db1340>


  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 619, in _interpret_response


    self._interpret_response_line(


    │    └ <function APIRequestor._interpret_response_line at 0x7f9639777280>


    └ <openai.api_requestor.APIRequestor object at 0x7f9635db1340>


  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 679, in _interpret_response_line


    raise self.handle_error_response(


          │    └ <function APIRequestor.handle_error_response at 0x7f9639771dc0>


          └ <openai.api_requestor.APIRequestor object at 0x7f9635db1340>




openai.error.InvalidRequestError: That model does not exist


2023-02-16 07:41:49.805 | INFO     | graia.ariadne.model:log:83 - 3365977521: [SEND][L(1162081675)] <- 出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。\nThat model does not exist
