### ISSUE TITLE
鉴权以及其他地方存在的一些问题

### ISSUE THREAD

**Issue by Lighitng** [takayama-lily/onebot#6]
1. 鉴权格式应为：
`POST / HTTP/1.1`
`X-Signature: sha1=...`

2. 使用ws时，可能会1000ms内无法建立连接但机器人已经启动。

3. Header可能不包含authorization（这个问题我不是很确定，但看了一下规范上是说一定会以query的形式传入一个access_token），这样的请求会被拒绝（403/401）。

4. 使用ws并启用心跳时，可能会在心跳时处于CLOSING/READYSTATE/CONNECTING等非打开状态，导致进程直接被kill掉。好吧，是说缺少try catch代码块。

**Comment by takayama-lily** [comment]
感谢提出。

关于2，现在会在登陆成功后再进行反向ws连接。
另外ws最好使用元事件`lifecycle.enable`和`lifecycle.disable`来判断机器人是否启动或掉线。

**Comment by Lighitng** [comment]
机器人倒是很少掉线，ws应该是掉线最多的地方，不启用心跳的时候经常断连，可能是被自动断开了。
