### ISSUE TITLE
首次登陆交互与容器化

### ISSUE THREAD

**Issue by Drew-Jay** [takayama-lily/onebot#7]
如题，首次登陆时因为需要交互，容器化放到docker内部署有点怪，希望首次的交互可以支持从配置文件读取账号密码，或者环境变量

**Comment by takayama-lily** [comment]
首次交互无法避免，因为不只是密码，还会需要输入验证码和解锁设备锁。
考虑到tx正在废弃图片验证码，未来可能还必须面对更复杂的滑动验证码

**Comment by Drew-Jay** [comment]
> 首次交互无法避免，因为不只是密码，还会需要输入验证码和解锁设备锁。
> 考虑到tx正在废弃图片验证码，未来可能还必须面对更复杂的滑动验证码

好的~Thanks♪(･ω･)ﾉ总之也容器化好啦

**Comment by Drew-Jay** [comment]
容器化构建的提了pr~

**Comment by Drew-Jay** [comment]
容器化已merge
