### ISSUE TITLE
请问项目支持使用代理吗？

### ISSUE THREAD

**Issue by 15x15G** [takayama-lily/onebot#8]
如果已经支持的话，应该在哪里设置？

**Comment by takayama-lily** [comment]
qq的通信是直接基于tcp协议的，可以通过ssh工具的端口转发或其他tcp代理工具实现代理效果。

例如你无法直接访问外网，ssh登陆一台可以访问外网的机器
ping msfwifi.3g.qq.com
在端口转发配置里将解析到的ip的8080端口映射到本地8080
hosts里配置msfwifi.3g.qq.com指向127.0.0.1即可

**Comment by 15x15G** [comment]
抱歉，不是这个问题，我好像issue发错地方了，应该发在oicq
具体问题是，客户端在国内，使用CQ码下载网络图片（比如推特的图片）需要通过代理才能下载，如何在程序中设置代理？
（已经开着梯子了但是程序似乎不走）

搜索了下似乎需要用到global-tunnel，有具体的修改配置方法吗？

试着直接在main.js里按说明加入globalTunnel了但是下载图片会报错The "listener" argument must be of type function. Received an instance of Object  不知道还有哪里错了或者要改

**Comment by takayama-lily** [comment]
使用代理请求网络资源暂时还没支持，没有配置方法。
另外你用的是 https://www.npmjs.com/package/global-tunnel-ng ？

**Comment by 15x15G** [comment]
对，我看这个好像能配置代理来着
